webtalk_init -webtalk_dir /home/diego/Escritorio/Sistema_empotrado_basico_ejercicio_2/SistemaEmpotradoPicoblaze/SistemaEmpotradoPicoblaze.sim/sim_1/behav/xsim/xsim.dir/Sistema_empotrado_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Nov 17 15:57:51 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2c8a3d8f-0add-4173-87e8-c2b03c57142c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "62c634ce7aa84fa29138e7c8a0774e9c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "47" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "LinuxMint" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Linux Mint 19.3 Tricia" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3304.387 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "4752530 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "54.00_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "135840_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3946073886 -regid "" -xml /home/diego/Escritorio/Sistema_empotrado_basico_ejercicio_2/SistemaEmpotradoPicoblaze/SistemaEmpotradoPicoblaze.sim/sim_1/behav/xsim/xsim.dir/Sistema_empotrado_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/diego/Escritorio/Sistema_empotrado_basico_ejercicio_2/SistemaEmpotradoPicoblaze/SistemaEmpotradoPicoblaze.sim/sim_1/behav/xsim/xsim.dir/Sistema_empotrado_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/diego/Escritorio/Sistema_empotrado_basico_ejercicio_2/SistemaEmpotradoPicoblaze/SistemaEmpotradoPicoblaze.sim/sim_1/behav/xsim/xsim.dir/Sistema_empotrado_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
